---
- name: Deploy Application
  hosts: all
  become: yes
  gather_facts: no
  # vars:
  #   tf_value_1
  pre_tasks:
    - name: Wait up to 120 seconds for target connection to become reachable/usable
      ansible.builtin.wait_for_connection:
        timeout: 120

  tasks:
    - debug:
        msg: "Value from Terraform: {{ tf_value_1 | default('no value found') }}"

    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present


    - name: Make sure nginx service is enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure nginx root is /var/www/html/
      ansible.builtin.copy:
        content: |
          server {
            root /var/www/html;
          }
        dest: /etc/nginx/conf.d/default.conf
        mode: '0644'
      notify: Restart nginx

    - name: Copy application files to nginx root
      ansible.builtin.copy:
        src: app/
        dest: /var/www/html/
        mode: '0644'
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
